---

- name: Check current docker-compose version
  ansible.builtin.command: docker-compose --version
  register: check_docker_compose_version
  changed_when: false
  failed_when: false
  check_mode: false

- name: Get current docker-compose version
  ansible.builtin.set_fact:
    docker_compose_current_version: "{{ check_docker_compose_version.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"

- name: Test docker-compose is installed
  ansible.builtin.assert:
    that:
      - docker_compose_current_version is version(docker_compose_version, '=')
