---
- name: Install the necessary dependencies to activate the Docker module
  ansible.builtin.package:
    name:
      - python3-setuptools
      - python3-requests
  when: docker_module_enabled

- name: Install the necessary dependencies to activate the docker-compose module
  ansible.builtin.package:
    name: "docker-compose={{ docker_compose_version }}"
  when: docker_compose_module_enabled

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include setup-docker-Debian task
  ansible.builtin.include_tasks: setup-docker-Debian.yml
  when: ansible_os_family == 'Debian'
