---

- name: Check current docker-compose version
  ansible.builtin.command: docker-compose --version
  register: check_docker_compose_version
  changed_when: false
  failed_when: false
  check_mode: false

- name: Get current docker-compose version
  ansible.builtin.set_fact:
    docker_compose_current_version: "{{ check_docker_compose_version.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
  when:
    - check_docker_compose_version.rc == 0

- name: Install or upgrade docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    force: true
  when: >
    docker_compose_current_version is not defined
    or docker_compose_current_version is version(docker_compose_version, '<')
